### ISSUE TITLE
PDF Report Generation / Report Template System.

### ISSUE THREAD

**Issue by AlexKollar** [SSGOrg/Navi#10]
Through my discussions with CSI Linux other methods of exporting Navi's reports have been brought to my attention. With a heavy emphasis on initial file output being .odt which will be converted to PDF for final report. 

- [ ] Find a way to implement **python-odf** into Navi 
- [ ] Find a way to generate a report using odt variables similar to how Navi currently outputs a .txt file.
- [ ]  Output the final odt file to PDF 
- [ ]  As a side note we should setup a custom directory for Navi's generated reports. 

Over time this system will need to be expandable so we can build custom templates.

**Comment by marvhus** [comment]
The ways we could do this is:
- we could directly generate a PDF using some library
- we could generate a PDF though some intermediate thing like TeX
