### ISSUE TITLE
Convert all os.system methods to Subprocess while keeping current functionality.

### ISSUE THREAD

**Issue by AlexKollar** [SSGOrg/Navi#14]
Proposed by: @FoxIDK  | InfosecWriter  
  
Due to `os.system` becoming deprecated. It would be a good idea to change all of the `os.system()` over to `subprocess`  
The major question is how do we do this without killing the whole 'conversation log' that Navi currently has. I don't want it to open a new Navi instance or window every time we call a /command or /clear. This also yields cleaner code and future proofs Navi's security.

**Comment by FoxIDK** [comment]
Should do a 'suggested' tag and then you can tag it as a community suggestion so people get ideal credit for the contribution. Even if it's minor.

**Comment by AlexKollar** [comment]
Noted will be adding.
