### ISSUE TITLE
Fix Navi's Ability to Pause GPT while executing custom commands

### ISSUE THREAD

**Issue by AlexKollar** [SSGorg/Navi#4]
### Issue:   
Right now we have it setup that all of the custom commands basically exit Navi, got into the custom script executes it and then returns to a fresh run of navi. It would be far better if this was all able to be done on one run instead of relying on subprocessing and breaking away from Navi. This way it all looks like one long conversation with Navi helping with tasks.

**Comment by marvhus** [comment]
Fixed in #7 (I just made a if statement to see if it starts with a /  if it is, then it is considered a command and this doesn't happen)
