### ISSUE TITLE
Navi wont register files in its directory unless you launch from the directory. 

### ISSUE THREAD

**Issue by AlexKollar** [SSGorg/Navi#5]
As of present if you launch navi from anywhere in the command line it will not let you use custom / commands as it does not register the file being in the directory you launched from. 

Will be working on proper install script in the next few days. 

For now the alias to get it to run properly is: 
`alias navi = cd ~/git/Navi/NaviCode && python3 main.py`

**Comment by marvhus** [comment]
use this:

os.path.abspath(os.path.dirname(__file__))

**Comment by AlexKollar** [comment]
By all mean you are more than welcome to dig in as well. @marvhus im actually shocked it got as far as it did. 

I'm trying to get it that I can run commands without GPT spitting output it thinks is relevant to the command issued.

**Comment by marvhus** [comment]
Fixed in #7
